# Generated by Django 3.2.7 on 2021-10-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='titles',
            new_name='title',
        ),
    ]
